### PR TITLE
【確認待ち】Sentences and lower case tuning

### PR DESCRIPTION
**Pull request by kurudrive**
<del>ブロック名の単語の最初の文字を大文字に統一したのとブロックの説明の微調整のみです</del>

Sentences and lower case tuning

### CODE REVIEW

**Comment by shimotmk** [comment]
@kurudrive 
Thank you for your correction.
However, if I want to fix it, I would like to match it with the core (Gutenberg).

Copy Button setting → Settings
https://github.com/WordPress/gutenberg/pull/40275

I don't think it's a good idea to use capital letters in sentences.
https://github.com/WordPress/gutenberg/issues/8888
https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/documentation/copy-guide.md#five-pay-attention-to-capitalization

Inner block → Inner blocks
https://github.com/WordPress/gutenberg/blob/fa3233c114da83b93da8d9da176425516511e64c/packages/block-editor/src/hooks/layout.js#L164

**Comment by kurudrive** [comment]
@shimotmk 

Thank you for your review.

> Copy Button setting → Settings
> Inner block → Inner blocks

Oh, I see, you have huge knowledge with Gutenberg.
I fixed it!!

> I don't think it's a good idea to use capital letters in sentences.

I see, but ... the reason of I was changed  it was block name is "noun".
( This is to make it easier for users to understand that it is a "block name". )
WordPress is not write "Wordpress" right?

I'll let you make the final decision about this repository.

**Comment by shimotmk** [comment]
@kurudrive
> WordPress is not write "Wordpress" right?

That is an incontestable truth.

There was lowercase case when using block titles in sentences.
https://github.com/WordPress/gutenberg/blob/74d6b30b10814f589e5c957ee12071a94610eabc/packages/block-library/src/column/block.json#L7

My native language is Japanese, so I can't judge what's natural.
So I checked the core rules.

**Comment by kurudrive** [comment]
> There was lowercase case when using block titles in sentences.
> https://github.com/WordPress/gutenberg/blob/74d6b30b10814f589e5c957ee12071a94610eabc/packages/block-library/src/column/block.json#L7

I see. you are right 👍
In the sentences, the core using lower case about block name too, therefore I agree with use lower case.

I'll fix it.
just a moment :)

**Comment by kurudrive** [comment]
@shimotmk Fixed it 🙂

**Review by shimotmk — APPROVED** [review]
Thank you.
I think it's good, so I'm merging it.

**Pull request merged**
