### PR TITLE
【確認待ち】Update readme ( add english )

### PR DESCRIPTION
**Pull request by kurudrive**
Support for English-speaking developers

### CODE REVIEW

**Comment by shimotmk** [comment]
@kurudrive 
I feel that README.md is unnecessary because there is readme.txt.

**Comment by kurudrive** [comment]
@shimotmk 

I feel README.md is necessary for the visitor who access to this GitHub. Don't you think?

**Comment by shimotmk** [comment]
@kurudrive
I didn't need it because there is no more important information than readme.txt at the moment.

**Comment by kurudrive** [comment]
@shimotmk 

Oh...really?

Sure, this README.md include only few information...but...

for example...

If the other developer's repository( GitHub repository  home page ) written by Nepali(it means can't understand) , then you feel it loose the interest read more right?

I think README.md is the entrance of the repository, then I feel it better for write with english not only Japanese.

But, this project(repository) is almost yours.
If you don't need that, feel free to close this 🙂

**Comment by shimotmk** [comment]
@kurudrive 
> If the other developer's repository( GitHub repository home page ) written by Nepali(it means can't understand) , then you feel it loose the interest read more right?

Oh. Certainly there may be people who think so.

I don't think this line is necessary, so please delete it.🙏

> The code is below.
https://github.com/vektor-inc/vk-simple-copy-block

**Comment by kurudrive** [comment]
> I don't think this line is necessary, so please delete it.🙏
> 
> > The code is below.
> > https://github.com/vektor-inc/vk-simple-copy-block

Oh, you certainly don't need it. I agree.

I was deleted 🙂

**Comment by shimotmk** [comment]
@kurudrive
> A block to copy the code of the block inside the copy target.

I want to match the text here with readme.txt.

https://github.com/vektor-inc/vk-simple-copy-block/blob/dab969534ab7e8681998a009a267d6bf5a80376a/readme.txt#LL14C1-L14C62

Maybe need to fix my Japanese too.

Sorry for my mistake.🙇‍♂️

**Comment by kurudrive** [comment]
@shimotmk Is this what you meant?

https://github.com/vektor-inc/vk-simple-copy-block/pull/18/commits/4cdf87522967ade1e09e8698309e1c5ce51cbeeb

**Review by shimotmk — APPROVED** [review]
Thank you.
I think it's good, so I'm merging it.

**Pull request merged**
